POST http://localhost:4000/store/hqqbtAKm1idQWUZxWXUeqYNGL1E2/addItem 
Content-Type: application/json

{
  "description":"a blue mouse",
  "name":"mouse",
  "price":25,
  "quantity":50
}

###

GET http://localhost:4000/store/hqqbtAKm1idQWUZxWXUeqYNGL1E2/getItems

###

GET http://localhost:4000/item/yvHp55vYaQAIsPELawbe

###

PUT http://localhost:4000/store/hqqbtAKm1idQWUZxWXUeqYNGL1E2/BrwxY3b9KtQc02pNkiHG/update
Content-Type: application/json

{
  "update":{
    "price":23,
    "description":"A mouse"
  }
}

###

DELETE http://localhost:4000/store/hqqbtAKm1idQWUZxWXUeqYNGL1E2/BrwxY3b9KtQc02pNkiHG/delete

###


GET http://localhost:4000/item/search/mouse

###


